### ISSUE TITLE
Is GPU necessary?

### ISSUE THREAD

**Issue by Chunting** [Souphis/mobile_robot_rl#7]
Hi Souphis,
I'm interested in the project, but I don't have a GPU, is it necessary?
Because you install tensorflow-gpu, so I just wana make a double check.

Thanks, 
Chunting

**Comment by gbartyzel** [comment]
No, it is not necessary ;) But maybe you can try the version with pytorch instead of tensorflow (it's old and obsolate).
Btw, sorry for this late answer, busy time right now ;)
