### ISSUE TITLE
Is there a main.py?

### ISSUE THREAD

**Issue by woosuk1103** [Souphis/mobile_robot_rl#8]
Hello, I'm studying RL in V-rep simulation env. and interested in your project

During following the guidelines you suggested, I found "python main.py ~~"

however, I cannot find any file which is "main.py" in your git file and cannot run the simulation..

Could you give me any recommendations?

Thanks in advance :)

**Comment by woosuk1103** [comment]
> Hello, I'm studying RL in V-rep simulation env. and interested in your project
> 
> During following the guidelines you suggested, I found "python main.py ~~"
> 
> however, I cannot find any file which is "main.py" in your git file and cannot run the simulation..
> 
> Could you give me any recommendations?
> 
> Thanks in advance :)

**Comment by woosuk1103** [comment]
Sorry for interrupting, I mean "python main.py --train" not "python main.py ~~"

**Comment by gbartyzel** [comment]
Oh well, I didn't update README, in new version there is run.py instead of main.py :)

**Comment by woosuk1103** [comment]
Thank you for immediate reply! :)
But can I ask you another question?

As you suggested above, I run the code "python run.py --train" (virtual env(python3.6) in ubuntu 18.04)
But it is only saying 'ImportError: cannot import name 'PyRep'

Thus, I downloaded PyRep via "pip install PyRep" and rebooted for several times, yet cannot run the code, though.
Is there any keys for handling this situation?

Thanks in advance. Your comments are really helping me :)

**Comment by gbartyzel** [comment]
You should install pyrep from github repo not from pip :)

**Comment by woosuk1103** [comment]
Thanks a lot!
